version: "3.8"

services:
  server:
    image: address_book_${TARGET_ENV-development}:${IMAGE_TAG-latest}
    volumes:
      - ../src/:/srv/src/
    env_file:
      - local.env
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: postgres:14.0-alpine3.14
    environment:
      POSTGRES_DB: server
      POSTGRES_USER: server
      POSTGRES_PASSWORD: server
    volumes:
      - data:/var/lib/postgresql/data

volumes:
  data:
