# Generated by Django 3.2.8 on 2021-10-10 18:20

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('country', models.CharField(max_length=128)),
                ('state', models.CharField(blank=True, max_length=128)),
                ('city', models.CharField(max_length=128)),
                ('zip_code', models.CharField(max_length=32)),
                ('address_one', models.CharField(max_length=1024)),
                ('address_two', models.CharField(blank=True, max_length=1024)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'address',
                'verbose_name_plural': 'addresses',
                'db_table': 'addresses',
                'ordering': ('created_at',),
                'get_latest_by': 'created_at',
            },
        ),
        migrations.AddIndex(
            model_name='address',
            index=models.Index(fields=['uuid'], name='addresses_uuid_19b7ce_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='address',
            unique_together={('zip_code', 'address_one')},
        ),
    ]
