# Generated by Django 3.2.8 on 2021-10-12 21:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=128)),
                ('state', models.CharField(blank=True, max_length=128)),
                ('city', models.CharField(max_length=128)),
                ('zip_code', models.CharField(max_length=32)),
                ('address_one', models.CharField(max_length=1024)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'address',
                'verbose_name_plural': 'addresses',
                'db_table': 'addresses',
                'ordering': ('created_at',),
                'get_latest_by': 'created_at',
            },
        ),
        migrations.CreateModel(
            name='UserAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('additional_address_data', models.CharField(blank=True, max_length=1024)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='address.address')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'user address',
                'verbose_name_plural': 'user addresses',
                'db_table': 'user_addresses',
                'ordering': ('created_at',),
                'get_latest_by': 'created_at',
            },
        ),
        migrations.AddField(
            model_name='address',
            name='users',
            field=models.ManyToManyField(through='address.UserAddress', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='useraddress',
            index=models.Index(fields=['uuid'], name='user_addres_uuid_f19610_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='useraddress',
            unique_together={('user', 'address')},
        ),
        migrations.AlterUniqueTogether(
            name='address',
            unique_together={('country', 'state', 'city', 'zip_code', 'address_one')},
        ),
    ]
