# Generated by Django 3.2.8 on 2021-10-12 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0002_auto_20211011_2015'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='address',
            unique_together={('country', 'zip_code', 'address_one')},
        ),
    ]
